### ISSUE TITLE
Inspector returns false for PermissionCheck on iOS 9.3.5

### ISSUE THREAD

**Issue by mrfrasier** [myflashlab/ANE-Inspector-Tool#1]
I have an iPhone 6S runnong iOS 9.3.5

I dumbed my code down to figure out why I wasn't going into the Permission check code, and discovered this.

trace( "Checking with inspector", Inspector.check( PermissionCheck ) );
if( Inspector.check( PermissionCheck ) ){
.... do stuff ....
}

In the output, I'm actually receiving:

"Checking with inspector false"

Which explains why the code inside the conditional wasn't executing. Any reason why false would be returned on an iOS device running 9.3.5?

**Comment by myflashlab** [comment]
When the inspector returns `false`, you can trace out the reason by calling 

``` actionscript
trace("Inspector.lastError = " + Inspector.lastError);
```

**Comment by mrfrasier** [comment]
Result:

> Checking with inspector false
> Inspector's last error: PermissionCheck ANE version is newer than the Inspector! You need to update the Inspector ANE. It's free to download! https://github.com/myflashlab/common-dependencies-ANE

Inspector is not listed at that URL. In my project, I have:
Inspector: 1.0.2
PermissionCheck: 1.0.1

I checked your site and the latest inspector is 1.0.3, so I upgraded to that and things seem to work now. However, the newest inspector was just released 2 days ago, and as you can see I made this post 5 days ago...

**Comment by myflashlab** [comment]
hmm, maybe we had missed to include the latest version of the permission check to the last inspector version... Sorry for the confusion. Sometimes such small mistakes happen. We're happy that it's all working fine now.
