### ISSUE TITLE
(Bug) Variable Firebase is not defined.

### ISSUE THREAD

**Issue by mshaffer12882** [myflashlab/ANE-Inspector-Tool#2]
Getting this error:
[Fault] exception, information=ReferenceError: Error #1065: Variable Firebase is not defined.

When I run this code:
if( !Inspector.check(Auth, true, true) )
            {
                trace( "Inspector.lastError = " + Inspector.lastError );
                return;
            }

**Comment by myflashlab** [comment]
Thanks for reporting this. Please update to V1.0.14 and this should be fixed now.

**Comment by mshaffer12882** [comment]
I can confirm it is working.  Thanks for the fast fix!
